openapi: 3.1.0  
info:  
 title: Minimal Graph API  
 version: v1  

paths:  
 /execute:  
   post:  
     summary: Execute a Minimal Graph API query  
     requestBody:  
       required: true  
       content:  
         application/json:  
           schema:  
             $ref: '#/components/schemas/User'  
           examples:  
             BasicReadAction:  
               summary: Find users whose name contains "1"  
               value:  
                 type: "read.user"  
                 entity: {}  
                 filters:  
                   - "name.contains(1)"  
     responses:  
       '200':  
         description: successful execution  
         content:  
           application/json:  
             schema:  
               type: object  

components:  
 schemas:  
   BasicReadAction:  
     type: object  
     properties:  
       type:  
         type: string  
         description: operation to perform, e.g. "read.user"  
       entity:  
         type: object  
         description: payload object (may be empty)  
       filters:  
         type: array  
         description: list of filter expressions  
         items:  
           type: string  
     required:  
       - type  
       - filters
   User:
      type: object
      properties:
        Id:
          type: integer
          format: int64
          description: Unique user identifier
        Name:
          type: string
        Surname:
          type: string
        DateOfBirth:
          type: string
          format: date
        Email:
          type: string
          format: email
        CreatedOn:
          type: string
          format: date-time
        CreatedBy:
          type: string
        ModifiedOn:
          type: string
          format: date-time
        ModifiedBy:
          type: string
        DeletedOn:
          type: string
          format: date-time
          nullable: true
        DeletedBy:
          type: string
          nullable: true
        Addresses:
          type: array
          items:
            #$ref: '#/components/schemas/Address'
        Articles:
          type: array
          items:
            #$ref: '#/components/schemas/Article'
        Friends:
          type: array
          items:
            #$ref: '#/components/schemas/User'
      required:
        - Id
        - Name
        - Surname
        - Email
